### PR TITLE
docs(OWNERS): add myself to the owners file

### PR DESCRIPTION
**Pull request by leogr**
Since I'm a Falco core maintainer, I would like to become an owner of this repository to help with its maintenance.

Thank you!

### CODE REVIEW

**Comment by leogr** [comment]
cc @kris-nova @fntlnz @leodido 
Anyone up for this? :pray:

**Comment by leogr** [comment]
ping @kris-nova @fntlnz @leodido again

**Comment by krisnova** [comment]
Thank you @leogr for bringing this to my attention. Do we still need this merged?

**Comment by leogr** [comment]
/reopen

@kris-nova yes, please. It will allow me to manage this repository. Thank you :pray: 

Anyway, we are proposing to archive this repository. See https://github.com/falcosecurity/evolution/issues/154 (Btw, what do you think about that? pls reply to the other issue :smiley_cat:) So, eventually, we will archive it, but having the possibility to manage it would still be useful for me.

**Review by krisnova — APPROVED** [review]

**Pull request merged**
